[package]
org = "ballerina_guides"
name = "ftgo_database_init"
version = "1.0.0"
authors = ["WSO2"]
distribution = "2201.0.0"

[build-options]
observabilityIncluded = true

[[platform.java11.dependency]]
groupId = "mysql"
artifactId = "mysql-connector-java"
version = "8.0.26"
